setup.py

It is needed to use mailman.py

Add requests as dep in setup.py

---

colab/templates/base.html
colab/templates/header.html

There was header info in base.html. We extracted it and removed a blank row.

Cleaned up HTML and extracted header

---

colab/accounts/templates/accounts/user_detail.html
colab/static/css/screen.css

Made it more specific to colab

Renamed vcard to colab-vcard

---

setup.py

Signed-off-by: Alexandre Barbosa <alexandreab@live.com>
Signed-off-by: Lucas Kanashiro <kanashiro.duarte@gmail.com>
Signed-off-by: Sergio Oliveira <seocam@gmail.com>

Bump both Celery and Colab version

---

colab/plugins/data/tasks.py

Signed-off-by: Lucas Moura <lucas.moura128@gmail.com>

Fixed flake8 for plugins/data/tasks.py

---

colab/plugins/utils/apps.py

Signed-off-by: Gustavo Jaruga <darksshades@gmail.com>

Change signal prototype to equal plugins methods

---

docs/source/user.rst

- Updated how the URL should be formatted

Updated plugins documentation

---

colab/accounts/filters.py
colab/plugins/utils/filters_importer.py
colab/search/forms.py
colab/search/templates/search/includes/search_filters.html
colab/search/templates/search/search.html
colab/search/tests.py
colab/search/views.py
colab/super_archives/filters.py

Make filters dynamic. app/plugins define its filters.

Search filters

---

colab/search/forms.py
colab/search/tests.py
colab/super_archives/filters.py

Need to first merge search_filters

Multiple filters refactor

---

colab/super_archives/views.py

Signed-off-by: Gustavo Jaruga <darksshades@gmail.com>
Signed-off-by: Alexandre Barbosa <alexandreab@live.com>

Fix send mail through interface

---

colab/widgets/widget_manager.py

Fix serve wrong widget when multiples simultaneous connections due to using the same static widget

Fix possible error when many simultaneous requests(Widgets)

---

colab/widgets/templatetags/widgets_tag.py
colab/widgets/widget_manager.py
docs/source/dev.rst

Signed-off-by: Luiz Oliveira <ziuloliveira@gmail.com>
Signed-off-by: Macartur Sousa <macartur.sc@gmail.com>

Refactored widgets to receive **kwargs

---

colab/super_archives/fixtures/test_user.json
colab/super_archives/tests/test_email_validation.py
colab/super_archives/views.py

Fixing issue https://github.com/colab/colab/issues/98

Testing email validation view

---

docs/source/plugindev.rst

Signed-off-by: Alexandre Barbosa <alexandreab@live.com>
Signed-off-by: Lucas Moura <lucas.moura128@gmail.com>

Update Search Documentation

---

colab/static/css/header.css
colab/static/css/screen.css
colab/templates/base.html

Signed-off-by: Carlos Oliveira <carlospecter@gmail.com>

Split screen css link to base html

---

colab/accounts/templates/accounts/user_detail.html

Fix https://github.com/colab/colab/issues/117

Fixing user profile blocks

---

colab/plugins/utils/apps.py
colab/plugins/utils/tests/test_apps.py
docs/source/plugindev.rst
docs/source/user.rst

Removing namespace from colab settings

Removing namespace

---

colab/accounts/forms.py
colab/accounts/models.py
colab/accounts/signals.py
colab/accounts/tests/test_user.py
colab/accounts/urls.py
colab/accounts/views.py

Both signals send a user instance and the plain password.

Send Django signals when user is created and password is changed

---

colab/accounts/forms.py
colab/accounts/models.py
colab/accounts/signals.py
colab/accounts/tests/test_user.py
colab/accounts/urls.py

Reverts colab/colab#119
Wrong base branch :P

Revert "Send Django signals when user is created and password is changed"

---

colab/accounts/forms.py
colab/accounts/models.py
colab/accounts/signals.py
colab/accounts/tests/test_user.py
colab/accounts/urls.py
colab/accounts/views.py

Doing the pull request https://github.com/colab/colab/pull/119 in the right branch

Send signal when password is changed

---

colab/accounts/templates/accounts/user_update_form.html

Signed-off-by: Gustavo Jaruga <darksshades@gmail.com>

Remove widget for profile tabs

---

colab/accounts/templates/accounts/manage_subscriptions.html

[issue: #126]
Signed-off-by: Carlos Coêlho <carlosoliveira@duzeru.org>

Expand column width for email subscriptions

---

colab/super_archives/templates/superarchives/thread-dashboard.html

Signed-off-by: Matheus Fernandes <matheus.souza.fernandes@gmail.com>

Fixed thread list message preview

---

colab/accounts/views.py
colab/home/views.py
colab/plugins/utils/collaborations.py
colab/super_archives/utils/collaborations.py

Signed-off-by: Macartur Sousa <macartur.sc@gmail.com>
Signed-off-by: Sergio Oliveira <seocam@seocam.com>

Moved collaboration to super_archives and plugins

---

colab/conf/plugin_template/setup.py
colab/conf/plugin_template/src/app_name/__init__.py
colab/conf/plugin_template/src/app_name/apps.py
colab/conf/plugin_template/src/app_name/data_importer.py
colab/conf/plugin_template/src/app_name/diazo.xml
colab/conf/plugin_template/src/app_name/models.py
colab/conf/plugin_template/src/app_name/search_indexes.py
colab/conf/plugin_template/src/app_name/urls.py
colab/conf/plugin_template/src/app_name/views.py
colab/conf/plugin_template/tests/colab_settings.py
colab/conf/plugin_template/tests/plugins.d/app_name.py
colab/conf/plugin_template/tests/runtests.py
colab/conf/plugin_template/tests/test_plugin.py
colab/management/commands/startplugin.py
colab/management/tests/test_startplugin.py
docs/source/plugindev.rst
setup.cfg

startplugin it's a command that generates the base of a Colab plugin.
Just like django's startapp and startproject.
Signed-off-by: Sergio Oliveira <sergio@tracy.com.br>

Implemented startplugin command

---

colab/accounts/templates/accounts/user_detail.html
colab/accounts/templates/registration/password_reset_complete_custom.html
colab/accounts/templates/registration/password_reset_confirm_custom.html
colab/accounts/templates/registration/password_reset_done_custom.html
colab/search/templates/search/search.html
colab/super_archives/templates/message-thread.html
colab/templates/base.html
colab/templates/home.html

If user wants to override just the pagetitle it should use block pagetitle
instead of block title
<issue: #151>

Added possibility to override full title

---

colab/super_archives/tests/test_mailinglist_view.py
colab/super_archives/views.py

Signed-off-by: Carlos Coelho <carlos@pencillabs.com>

Made latest default ordering for list view

---

colab/accounts/tasks.py
colab/accounts/tests/test_forms.py
colab/accounts/tests/test_tasks.py
colab/settings.py
docs/source/user.rst

closes https://softwarepublico.gov.br/gitlab/softwarepublico/softwarepublico/issues/247

User verification

---

colab/plugins/utils/collaborations.py
colab/super_archives/tests/test_utils_collaborations.py

Signed-off-by: Gustavo Jaruga Cruz <darksshades@gmail.com>

Fix collaboration graph count

---

colab/utils/conf.py
colab/utils/tests/settings.d/test.py
colab/utils/tests/test_conf.py
tests/run.py

Fixing local settings.d import on tests

---

colab/templates/footer.html

There was a horizontal scrolling in footer.
Moving row to a separate div and putting it inside a container solved it.

Fix usage of container and row in footer

---

colab/plugins/context_processors.py
colab/plugins/tests/test_context_processors.py
colab/settings.py
colab/templates/base.html
colab/templates/header-slim.html
docs/source/plugindev.rst

Now, plugins can change the colab header when your pages are accessed

Change header

---

colab/accounts/templates/accounts/user_update_form.html

Fix Add/Erase and resend verification buttons on edit profile with colab without plugins.
Fix jQuery not found problem.

Fix jQuery and add/remove emails buttons

---

colab/accounts/models.py
colab/accounts/signals.py
colab/accounts/templates/accounts/user_update_form.html
colab/static/css/screen.css

Needs to merge https://softwarepublico.gov.br/gitlab/softwarepublico/softwarepublico/merge_requests/238/diffs

Update user info

---

setup.py

Signed-off-by: Tallys Martins <tallysmartins@gmail.com>

Moves test dependencies to correct place

---

colab/search/forms.py

Add some relevance in search. Matches in title have precedence than description.
@chaws could you review it?

Fix solr boosting

---

colab/accounts/tests/test_user.py
colab/accounts/tests/test_view_signup.py
colab/accounts/urls.py
colab/accounts/views.py

Changing the signup view to a class-based view on accounts/views.py.
Signed-off-by: Italo Paiva <italosensei@hotmail.com>
Signed-off-by: Emiliemorais <emilie.mo@hotmail.com>

Turning signup view to class-based view
